name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.5
      - name: Install rustfmt and clippy
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      # - name: Install cargo audit
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: cargo-audit
      # - name: Run cargo audit
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: audit
      # - name: Install cargo pants
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: cargo-pants
      # - name: Run cargo pants                ENABLE ME
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: pants
